FROM node:22-alpine
COPY glob-image-resize.tgz /tmp/glob-image-resize.tgz
RUN yarn global add /tmp/glob-image-resize.tgz \
    && rm /tmp/glob-image-resize.tgz
WORKDIR /images
ENTRYPOINT [ "glob-image-resize" ]
