name: Publish Docker image

on:
  push:
    tags:
      - v*

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: yarn install
      - run: yarn pack --filename glob-image-resize.tgz

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            liquidjs/glob-image-resize
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile.prebuild
          cache-from: type=gha
          cache-to: type=gha,mode=max
